[icons]
icons = "awesome4"

[[block]]
block = "keyboard_layout"
driver = "sway"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:15,rot_interval:0.5) |}"
format_alt = " $icon $prev {$title.str(max_w:15,rot_interval:0.5) $play $next |}"

[[block]]
block = "custom"
json = true
command = ''' echo "{\"icon\":\"ping\",\"text\":\"$(ping -c4 1.1.1.1 | tail -n1 | cut -d'/' -f5)\"}" '''
interval = 60
[[block]]
block = "net"
# format = " $icon {$signal_strength $ssid |Wired connection} $graph_up $graph_down"
format = " $icon {$signal_strength $ssid |Wired connection} ^icon_net_down $speed_down.eng(prefix:K) $graph_down $graph_up ^icon_net_up $speed_up.eng(prefix:K) "
# format = " $icon {$signal_strength $ssid $frequency|Wired connection}"

[[block]]
block = "github"
token = "****************************************"
format = " $icon $total.eng(w:1) "
info = ["total"]
warning = ["mention","review_requested"]
# hide_if_total_is_zero = true
[[block]]
block = "notify"
# format = " $icon {($notification_count.eng(w:1)) |}"
format = " $icon {($notification_count.eng(w:1)) |}"
driver = "swaync"
[[block.click]]
button = "left"
action = "show"

[[block]]
block = "packages"
package_manager = ["aur"]
interval = 600
error_interval = 300
format = " $icon Pac $aur "
format_singular = " $icon $total "
format_up_to_date = " $icon latest "
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "paru -Qu"

[[block]]
block = "load"
[[block]]
block = "nvidia_gpu"
format = "$icon $utilization $temperature"
[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
[[block]]
block = "temperature"
format = " $icon $max "
[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "

[[block.click]]
button = "right"
action = "toggle_paused"

[[block]]
block = "sound"
[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "
[[block]]
block = "battery"

[[block]]
block = "time"

# # $HOME/dev/others/base16/templates/base16-i3status-rust/colors/base16-gruvbox-dark-hard.toml
# # vi:syntax=toml
# # base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# # Gruvbox dark, hard by Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
# [theme]
# theme = "solarized-dark"
# [theme.overrides]
# idle_bg = "#1d2021"
# idle_fg = "#d5c4a1"
# info_bg = "#8ec07c"
# info_fg = "#1d2021"
# good_bg = "#b8bb26"
# good_fg = "#1d2021"
# warning_bg = "#fabd2f"
# warning_fg = "#1d2021"
# critical_bg = "#fb4934"
# critical_fg = "#1d2021"
# # The rest of the theme settings are left at default.
