general.import = [
  # "./themes/base24-gruvbox-dark.toml",
  "./themes/base16-gruber.toml",
]

[font]
size = 14

[font.normal]
family = "Iosevka Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 0
y = 0

[scrolling]
history = 0 
