theme = "ayu_mirage"

# create a new minor mode bound to `+`
[keys.normal."+"]
m = ":run-shell-command echo 2"
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"
n = ":run-shell-command echo 3"

[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

# [editor]
# line-number = "relative"
# color-modes = true
# # auto-completion = false

# # Do only on text files
# [editor.soft-wrap]
# enable = true
