theme = "gruber-darker"
# theme = "dracula"
# theme = "gruvbox_light_hard"
# theme = "tokyonight_day"

[editor]
mouse = false
line-number = "relative"
color-modes = true
# text-width = 80

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
# display-inlay-hints = false
# auto-signature-help = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
separator = "│"
left = ["mode", "spinner"]
center = ["file-name"]
right = ["position", "diagnostics", "workspace-diagnostics", "version-control"]

[keys.normal]
C-y = [
  ':sh rm -f /tmp/yazi-path',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/yazi-path',
  ':open %sh{cat /tmp/yazi-path}',
  ':redraw',
]

# Z = { Q = ":quit!", Z = ":x" }
# j = "move_char_left"
# i = "move_visual_line_up"
# l = "move_char_right"
# k = "move_visual_line_down"


[keys.insert]
"C-[" = "normal_mode"
"C-p" = "signature_help"

