# theme = "base16-gruvbox-dark-hard"

[editor]
line-number = "relative"
color-modes = true
# auto-completion = false

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[keys.normal.space]
q = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw",
]
Q = [
  ":sh rm -f /tmp/unique-file-u41ae14",
  ":insert-output yazi '%{workspace_directory}' --chooser-file=/tmp/unique-file-u41ae14",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-u41ae14}",
  ":redraw",
]

