[[language]]
name = "fish"
auto-format = false

[language-server]
clangd = { command = "clangd", args = [ "--clang-tidy" ] }

[language-server.rust-analyzer.config]
check = {command = "clippy", extraArgs = ["--", "-W", "clippy::unwrap_used", "-W", "clippy::expect_used", "-W", "clippy::pedantic", "-W", "clippy::nursery"]}

[[language]]
name = "c"
# auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "rust"
formatter = { command = "rustfmt" }

# [[language]]
# name = "julia"
# formatter = { command = "julia", timeout = 60, args = [ "-e", "using JuliaFormatter; println(\"Hello\", length(ARGS)); format(ARGS[1]);", ] }

# [language-server.julia]
# command = "julia"
# # args = [ "--project=@LanguageServer", "--startup-file=no", "--history-file=no", "-e", "using LanguageServer; runserver()" ]
# args = [ "--project=.", "--startup-file=no", "--history-file=no", "-e", "using LanguageServer; runserver()" ]

# [[language]]
# name = "markdown"
# # scope = "source.md"
# # injection-regex = "md|markdown"
# # file-types = ["md", "markdown", "PULLREQ_EDITMSG", "mkd", "mdwn", "mdown", "markdn", "mdtxt", "mdtext", "qmd", "workbook"]
# # roots = [".marksman.toml"]
# # language-servers = [ "marksman" ]
# indent = { tab-width = 2, unit = "  " }
